# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36afc3ee07b5b1f8d17de3a40eb1c8b599778b6c9c74988348705c28c3ebb207dcc4115d223ce06c5acbfc314b98acaa828daa54f0b0fa7307ac3d98655b4eed

test:
  secret_key_base: 82f4ff7e027c1eecfdfaec8daf29760862d50207d19ea6b938ebadd6b70fded0176cdb86d34a13b32fd74329484759dfe026fa8af5f300abcd9311af0c682fc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
